import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import LogoImage from '../../public/logo.jpg';

export const metadata: Metadata = {
  title: "Nom d'un chien à Court",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="flex flex-col justify-center items-center basis-full">
      <Image className="rounded-md m-4" src={LogoImage} alt="Logo Nom d'un chien"></Image>
      <nav className="flex">
        <ul className="flex">
          <Link className="text-2xl p-4 mx-0 rounded-md hover:bg-white active:bg-primary" href="/">Home</Link>
          <Link className="text-2xl p-4 mx-0 rounded-md hover:bg-white active:bg-primary" href="/">Présentation</Link>
          <Link className="text-2xl p-4 mx-0 rounded-md hover:bg-white active:bg-primary" href="/">Cours</Link >
          <Link className="text-2xl p-4 mx-0 rounded-md hover:bg-white active:bg-primary" href="/">Ballade active</Link>
          <Link className="text-2xl p-4 mx-0 rounded-md hover:bg-white active:bg-primary" href="/">Ressources</Link>
          <Link className="text-2xl p-4 mx-0 rounded-md hover:bg-white active:bg-primary" href="/">Nous trouver</Link>
          <Link className="text-2xl p-4 mx-0 rounded-md hover:bg-white active:bg-primary" href="/">Contact</Link>
        </ul>
      </nav>
      <hr className="w-4/5 h-px my-4 bg-primary border-0" />
    </header>
  );
}

function Footer() {
  return (
    <footer className="flex flex-col justify-center items-center basis-full">
      <hr className="w-4/5 h-px my-4 bg-primary border-0" />
      <ul className="flex">
        <li className="p-4"><b className="font-bold">Téléphone:</b> 032 497 98 04</li>
        <li className="p-4"><b className="font-bold">Natel:</b> 078 659 66 85</li>
        <li className="p-4"><b className="font-bold">Adresse mail:</b> <a href="mailto:info@nomd1chien.ch">info@nomd1chien.ch</a></li>
      </ul>
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
